"""Domínio industrial independente de UI e persistência.

Este pacote é deliberadamente livre de frameworks de apresentação para ser
reutilizado pela API Web, analytics e testes automatizados.
"""


from .manufacturing_rules import (
    AUTOMATIC_BREAKS,
    AUTOMATIC_BREAK_INTERRUPTION_TYPE,
    EQUIPMENT_FAILURE_STOP_GROUP,
    EXECUTING_APPOINTMENT_STATUSES,
    FORCED_UNPLANNED_STOP_REASONS,
    ManufacturingRules,
    NO_APPOINTMENT_STOP_REASON,
    OFFICIAL_WORK_WINDOW,
    OPEN_APPOINTMENT_STATUSES,
    OVERTIME_WINDOWS,
    PLANNED_STOP_GROUP_CODES,
    RESOURCE_WITHOUT_OP_STOP_REASON,
    SIGMANEST_LASER_MACHINE,
    SIGMANEST_PLASMA_MACHINE,
    SHIFT_END_BOUNDARIES,
    SHIFT_END_INTERRUPTION_TYPE,
    SHIFT_END_REASON,
    SHIFT_START_NO_DEMAND_REASON,
    SHIFT_START_NO_DEMAND_TYPE,
    STOP_CLASSIFICATION_COLORS,
    STOP_CLASSIFICATION_UI_TOKENS,
    SYSTEM_OPERATOR,
    planned_overtime_windows_from_intervals,
)

from .industrial import (
    AllocationStrategy,
    DataAvailability,
    EventCategory,
    IssueSeverity,
    PHYSICAL_STATE_VALUES,
    QuantityKind,
    ShiftWindowKind,
    StopClassification,
)
from .operator_state_machine import (
    ALLOWED_TRANSITIONS,
    GENERIC_INVALID_TRANSITION_CODE,
    InvalidTransition,
    OPERATOR_STATE_BY_STATUS,
    OPERATOR_STATUS_BY_STATE,
    OperatorAction,
    OperatorState,
    TransitionValidation,
    can_transition,
    explain_invalid_transition,
    operator_state_from_status,
    operator_status_for_state,
    resolve_operator_action,
    return_state_for_transition,
    validate_transition,
)

__all__ = [
    "AllocationStrategy",
    "DataAvailability",
    "EventCategory",
    "IssueSeverity",
    "PHYSICAL_STATE_VALUES",
    "QuantityKind",
    "ShiftWindowKind",
    "StopClassification",
    "ALLOWED_TRANSITIONS",
    "OPERATOR_STATE_BY_STATUS",
    "OPERATOR_STATUS_BY_STATE",
    "OperatorAction",
    "OperatorState",
    "TransitionValidation",
    "can_transition",
    "operator_state_from_status",
    "operator_status_for_state",
    "GENERIC_INVALID_TRANSITION_CODE",
    "InvalidTransition",
    "explain_invalid_transition",
    "resolve_operator_action",
    "return_state_for_transition",
    "validate_transition",
    "ManufacturingRules",
    "AUTOMATIC_BREAKS",
    "AUTOMATIC_BREAK_INTERRUPTION_TYPE",
    "EQUIPMENT_FAILURE_STOP_GROUP",
    "EXECUTING_APPOINTMENT_STATUSES",
    "OPEN_APPOINTMENT_STATUSES",
    "SIGMANEST_LASER_MACHINE",
    "SIGMANEST_PLASMA_MACHINE",
    "SHIFT_END_BOUNDARIES",
    "SHIFT_END_INTERRUPTION_TYPE",
    "SHIFT_END_REASON",
    "SHIFT_START_NO_DEMAND_REASON",
    "SHIFT_START_NO_DEMAND_TYPE",
    "SYSTEM_OPERATOR",
    "FORCED_UNPLANNED_STOP_REASONS",
    "NO_APPOINTMENT_STOP_REASON",
    "OFFICIAL_WORK_WINDOW",
    "OVERTIME_WINDOWS",
    "PLANNED_STOP_GROUP_CODES",
    "RESOURCE_WITHOUT_OP_STOP_REASON",
    "STOP_CLASSIFICATION_COLORS",
    "STOP_CLASSIFICATION_UI_TOKENS",
    "planned_overtime_windows_from_intervals",
]
